name: Test Spring Boot Application

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 which is compatible with Node.js 16 and 20

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Updated to v4 which is compatible with Node.js 20
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3  # Updated to v3 which is compatible with Node.js 16 and 20
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test with Maven
      run: mvn clean install
